import type { Metadata } from "next";
import { Alice, Poppins, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Navbar from "./components/shared/navbar";
import Footer from "./components/shared/footer";

// Alice font setup
const alice = Alice({
  weight: "400",
  variable: "--font-alice",
  subsets: ["latin"],
});

// Poppins font setup
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

// Bricolage Grotesque font setup
const bricolageGrotesque = Bricolage_Grotesque({
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: '--font-bricolage',
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "In The Visual",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alice.variable} ${poppins.variable} ${bricolageGrotesque.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
